### PR TITLE
Encode field numbers at compile time

### PR DESCRIPTION
**Pull request by j6carey**
...at the cost of some increased code size.

### CODE REVIEW

**Review by ixmatus — APPROVED** [review]

**Comment by riz0id** [comment]
@j6carey how do the inline pragmas benefit these instances?

**Comment by j6carey** [comment]
> @j6carey how do the inline pragmas benefit these instances?

@riz0id , Speed has increased as a result of these changes, but I'm hoping to make some further refinements to this PR to reduce the code size increase, which I have also measured.  The theory behind the speed increase is to get the encodings of the field numbers to be computed at compile time, and to reduce the number of non-inline function calls and their associated overhead (saving to the stack and then restoring).

**Review by riz0id — APPROVED** [review]

**Review by jcarr-awake — APPROVED** [review]
Looks good pending good benchmark results

**Comment by jcarr-awake** [comment]
Thanks for working to reduce the code size impact!

**Comment by j6carey** [comment]
The benchmark results are good--actually better than what I measured before, though they are relative to a different baseline, and that may be the reason.

**Pull request merged**
